name: HumineStaff
main: humine.com.main.StaffMain
author: [MizakiGaming, SDAChess]
version: 1.0.2a
api-version: 1.4.6
commands:
  invsee:
  endsee:
  annonce:
  vanish:
  voteban:
  automessage:
  lien:
  permission:
  tpsmonitor:
  upvote: